Client/Models/ErrorViewModel.cs
namespace Client.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Client/Controllers/AccountController.cs
using API.DTOs.Accounts;
using Client.Contracts;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;

namespace Client.Controllers;

public class AccountController : Controller
{
    private readonly IAccountRepository _accountRepository;
    public AccountController(IAccountRepository accountRepository)
    {
        _accountRepository = accountRepository;
    }
    [HttpGet]
    public IActionResult Login()
    {
        if (User.Identity.IsAuthenticated)
        {
            // Pengguna sudah login, lakukan tindakan sesuai kebijakan Anda
            return RedirectToAction("Index", "Home");
        }

        // Jika belum login, tampilkan halaman login
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginDto loginDto)
    {
        var result = await _accountRepository.Login(loginDto);
        if (result is null)
        {
            return RedirectToAction("Error", "Home");
        }
        else if (result.Code == 409)
        {
            ModelState.AddModelError(string.Empty, result.Message);
            return View();
        }
        else if (result.Code == 200)
        {
            HttpContext.Session.SetString("JWToken", result.Data.Token);
            return RedirectToAction("Index", "Home");
        }
        
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> Logout()
    {
        // Clear authentication cookies
        HttpContext.Session.Clear();
        return RedirectToAction("Index", "Home");
    }
}

Client/Controllers/EmployeeController.cs
using API.DTOs.Employees;
using API.Models;
using Client.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;

namespace Client.Controllers;

[Authorize(Roles = "Admin")]
public class EmployeeController : Controller
{
    private readonly IEmployeeRepository _employeeRepository;
    public EmployeeController(IEmployeeRepository employeeRepository)
    {
        _employeeRepository = employeeRepository;
    }
    public async Task<IActionResult> Index()
    {
        var result = await _employeeRepository.Get();
        var ListEmployee = new List<EmployeeDto>();

        if (result.Data != null)
        {
            ListEmployee = result.Data.Select(employee => (EmployeeDto)employee).ToList();
        }
        return View(ListEmployee);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(NewEmployeeDto newEmployee)
    {

        var result = await _employeeRepository.Post(newEmployee);
        if (result.Code == 200 )
        {
            TempData["Success"] = "Data berhasil masuk";
            return RedirectToAction(nameof(Index));
        }
        else if (result.Code == 400)
        {
            ModelState.AddModelError(string.Empty, result.Message);
            return View();
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid id)
    {
        var result = await _employeeRepository.Get(id);
        var ListEmployee = new UpdateEmployeeDto();
        if (result.Data != null)
        {
            ListEmployee = (UpdateEmployeeDto)result.Data;
        }
        return View(ListEmployee);
    }

    [HttpPost]
    public async Task<IActionResult>Update(UpdateEmployeeDto updateEmployee)
    {
        var result = await _employeeRepository.Put(updateEmployee.Guid, updateEmployee);
        if (result.Code == 200)
        {
            TempData["Success"] = $"Data has been Successfully Registered! - {result.Message}!";
            return RedirectToAction(nameof(Index));
        }

        TempData["Error"] = $"Failed to update data - {result.Message}!";
        return RedirectToAction(nameof(Edit));
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid guid)
    {
        var result = await _employeeRepository.Delete(guid);
        if (result.Code == 200)
        {
            TempData["Success"] = "Data Berhasil Dihapus";
        }
        else
        {
            TempData["Error"] = "Gagal Menghapus Data";
        }
        return RedirectToAction(nameof(Index));

    }

}

Client/Controllers/HomeController.cs
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("Unauthorized/")]
        public IActionResult Unauthorized()
        {
            return View("401");
        }

        [HttpGet("Forbidden/")]
        public IActionResult Forbidden()
        {
            return View("403");
        }

        [HttpGet("Notfound/")]
        public IActionResult Notfound()
        {
            return View("404");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Client/Controllers/LatihanController.cs
using Client.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;


namespace Client.Controllers
{
    [Authorize]
    public class LatihanController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Pokemon()
        {
            return View();
        }
        public IActionResult TableEmployee()
        {
            return View();
        }
    }
}

Client/Controllers/RegisterController.cs
using API.DTOs.Accounts;
using API.DTOs.Employees;
using Client.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers;

public class RegisterController : Controller
{
    private readonly IRegisterRepository _registerRepository;
    public RegisterController(IRegisterRepository registerRepository)
    {
        _registerRepository = registerRepository;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register(RegisterDto registerDto)
    {

        var result = await _registerRepository.Post(registerDto);
        if (result.Code == 200)
        {
            TempData["Success"] = "Data berhasil masuk";
            return RedirectToAction("Index","Employee");
        }
        else if (result.Code == 400)
        {
            ModelState.AddModelError(string.Empty, result.Message);
            return View();
        }
        return RedirectToAction("Index","Employee");
    }
}

Client/Views/Employee/Create.cshtml
@model API.DTOs.Employees.NewEmployeeDto

@{
    ViewData["Title"] = "Create";
    Layout = "_LayoutAdmin";
}

<h1>Create</h1>

<h4>NewEmployeeDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="/Employee/Create" method="POST" id="form-employee">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HiringDate" class="control-label"></label>
                <input asp-for="HiringDate" class="form-control" />
                <span asp-validation-for="HiringDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Client/Views/Employee/Edit.cshtml
@model API.DTOs.Employees.UpdateEmployeeDto

@{
    ViewData["Title"] = "Edit";
    Layout = "_LayoutAdmin";
}

<h1>Edit</h1>

<h4>UpdateEmployeeDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="/Employee/Update" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="Guid" class="control-label"></label>
                <input asp-for="Guid" class="form-control" readonly/>
                <span asp-validation-for="Guid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HiringDate" class="control-label"></label>
                <input asp-for="HiringDate" class="form-control" />
                <span asp-validation-for="HiringDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Client/Views/Home/401.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Unauthorized Access";
    Layout = "_LayoutError";
}
<h2 class="mb-2 mx-2">Unauthorized Access 🚫</h2>
<p class="mb-4 mx-2">Oops! 😖 You are not authorized to access this page.</p>
<p class="mb-4 mx-2">Please make sure you are logged in and have the necessary permissions to view this content.</p>
<a asp-controller="Home" asp-action="Index" class="btn btn-primary">Back to home</a>
<div class="mt-3">
    <img src="~/bootstrap/assets/img/illustrations/401.png"
         alt="page-misc-error-light"
         width="500"
         class="img-fluid"
         />
</div>

Client/Views/Home/403.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Access Forbidden";
    Layout = "_LayoutError";
}
<h2 class="mb-2 mx-2">Access Forbidden 🚫</h2>
<p class="mb-4 mx-2">Oops! 😖 You don't have permission to access this page or resource.</p>
<p class="mb-4 mx-2">Please make sure you have the necessary permissions to view this content.</p>
<a asp-controller="Home" asp-action="Index" class="btn btn-primary">Back to home</a>
<div class="mt-3">
    <img src="~/bootstrap/assets/img/illustrations/403.png"
         alt="page-misc-error-light"
         width="500"
         class="img-fluid" />
</div>

Client/Views/Home/404.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Not Found";
    Layout = "_LayoutError";
}
<h2 class="mb-2 mx-2">Page Not Found :(</h2>
<p class="mb-4 mx-2">Oops! 😖 The requested URL was not found on this server.</p>
<a asp-controller="Home" asp-action="Index" class="btn btn-primary">Back to home</a>
<div class="mt-3">
    <img src="~/bootstrap/assets/img/illustrations/404.png"
         alt="page-misc-error-light"
         width="500"
         class="img-fluid" />
</div>

Client/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Client/Views/Latihan/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_LayoutAdmin";
}

<div class="container d-flex flex-row mb-3" id="menuChart">
    <div class="card m-4 p-4" style="width:500px;max-width:700px">
        <div class="row g-0">
            <canvas id="myChart1" style="width:100%;max-width:700px"></canvas>
        </div>
    </div>
    <div class="card m-4 p-4" style="width:500px;max-width:700px">
        <div class="row g-0">
            <canvas id="myChart2" style="width:100%;max-width:700px"></canvas>
        </div>
    </div>
</div>


<div class="container row row-cols-2 row-cols-lg-5 g-2 g-lg-3" id="menu">
    <!-- Pokemon -->
    <div class="card mb-3 mr-3" style="max-width: 400px; width:auto;">
        <div class="row g-0 m-3">
            <div class="col m-0 p-0">
                <img src="https://cdn.icon-icons.com/icons2/851/PNG/512/Pokedex_tool_icon-icons.com_67529.png" class="img-thumbnail border-0" alt="..." style="max-width: 50px;">
            </div>
            <div class="col m-0 p-0 d-flex flex-column" style="max-width:100px">
                <a class="btn btn-primary" role="button" asp-area="" asp-controller="Latihan" asp-action="Pokemon">Open</a>
            </div>
        </div>
        <div class="row g-0 m-0">
            <div class="col m-0 p-0">
                <div class="card-body pt-0">
                    <h5 class="card-title">Pokedex</h5>
                    <p class="card-text fs-6">Tugas Pokemon API</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Table Employee -->
    <div class="card mb-3" style="max-width: 400px; width:auto;">
        <div class="row g-0 m-3">
            <div class="col m-0 p-0">
                <img src="https://aista.com/images/crud.jpeg" class="img-thumbnail border-0" alt="..." style="max-width: 100px;">
            </div>
            <div class="col m-0 p-0 d-flex flex-column" style="max-width:100px">
                <a class="btn btn-primary" role="button" asp-area="" asp-controller="Latihan" asp-action="TableEmployee">Open</a>
            </div>
        </div>
        <div class="row g-0 m-0">
            <div class="col m-0 p-0">
                <div class="card-body pt-0">
                    <h5 class="card-title">CRUD</h5>
                    <p class="card-text fs-6">Tugas Tabel Employee</p>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- grid -->
<div class="container-fluid text-center border border-primary m-auto" id="container">
    <div class="row m-10" id="row1">
        <div class="col border border-primary" id="col1">

            Why do we use it?
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

            Why do we use it?
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

            Why do we use it?
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).



        </div>
        <div class="col" id="col2">
            <div class="row m-0" id="row2">
                <div class="col border border-primary" id="col3">

                    Why do we use it?
                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

                </div>
                </div>
            <div class="row mt-20px mb-0 mx-0" id="row3">
                <div class="col border border-primary" id="col4">

                    Why do we use it?
                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).


                </div>
        </div>
    </div>
</div>
<div class="m-3">
     <button type="button" class="btn btn-primary" id="btn1">Blue</button>
     <button type="button" class="btn btn-danger" id="btn2">Red</button>
     <button type="button" class="btn btn-success" id="btn3">Green</button>
</div>

    <p class="h2 my-5 text-center">List Starwars</p>

<div>
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th scope="col">Number</th>
                    <th scope="col">Name</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Height</th>
                </tr>
            </thead>
            <tbody id="table-body">
            </tbody>
        </table>
</div>


    

Client/Views/Latihan/Pokemon.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_LayoutAdmin";
}
<!-- Pokedex -->
<div class="header mb-4">
    <div class="header-title">
        <h1 class="h1"> <span>  <img src="https://img.freepik.com/free-icon/pokeball_318-331350.jpg?w=2000" class="img-fluid" style="width: 50px; height: 50px;" alt="Logo"> </span>POKEDEX</h1>
    </div>
</div>

<div class="mb-4" id="data-pokemon-list">
    <div class="row row-cols-2 row-cols-lg-4" id="pokemon-list">
    </div>
</div>


<!-- Modal Pokemon -->
<div class="modal fade" id="detail-pokemon" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl text-white">
        <div class="modal-content">
            <div class="modal-header" style="color: #f05452;">
                <h5 class="modal-title" id="exampleModalLabel">Pokedex</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body position-relative bg-overlay bg-opacity-75 img-fluid" style="background-image: url('https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/813b6b5a-d48f-4d22-aa23-bb84ac52ccb6/d5c6eql-10a04956-ab30-463f-88a6-27afa9f85eb9.jpg/v1/fit/w_828,h_518,q_70,strp/pokeball_wallpaper_by_markitox_rox3r_d5c6eql-414w-2x.jpg');">
                <div class="container" id="detail-data-pokemon">
                    <div class="row">
                        <div class="col" id="pokemon-image">
                            Nama
                            Gambar
                        </div>
                        <div class="col" id="pokemon-detail">
                            <div class="container">
                                <div class="row m-0">
                                    <div class="col" id="type-pokemon">
                                        type
                                    </div>
                                </div>
                                <div class="row m-0">
                                    <div class="col" id="characteristics-pokemon">
                                        height + weight + color
                                    </div>
                                </div>
                                <div class="row m-0">
                                    <div class="col" id="status-pokemon">
                                        status
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Client.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Client</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Latihan" asp-action="Index">Latihan</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li id="loginButton" class="nav-item">
                                <a class="nav-link text-dark" href="/account/logout">logout</a>
                            </li>
                        }
                        else{
                        <li id="loginButton" class="nav-item">
                            <a class="nav-link text-dark" href="/account/login">Login</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Client/Views/Shared/_LayoutLatihan.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Client.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Client</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Latihan" asp-action="Index">Latihan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/affc631ccc.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>